[project]
name = "utils"
version = "0.1.0"
description = "Visualization utilities for Kuramoto simulation"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.0.0",
    "pyarrow>=14.0.0",
    "matplotlib>=3.7.0",
    "pillow>=10.0.0",
    "numpy>=1.24.0",
]
