[package]
name = "kuramoto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
arrow = "55.2.0"
ndarray = "0.16.1"
parquet = "55.2.0"
rand = "0.9.2"
rand_distr = "0.5.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
